env_name: "gym_examples/contGrid-v5_1"
state_dim: 3
action_dim: 1
action_range: [0, 6.28318]
F: 1
vel_field: "/home/rohit/Documents/Research/Planning_with_transformers/Decision_transformer/my-dec-transformer/data/HW_v7_l/raw_data/nT_120"
del_t: 1.
vmax_by_F: 1.
space_scale: 1
target_radius: 2

add_transition_noise_during_inf: False
noise_var: [0.1,0]

rtg_target: 60
rtg_scale: 1
dataset_name: "HW_v7_l"
dataset_path: "data/HW_v7_l/traj_data_for_model_5_trad2.pkl"
log_dir: "log"
params2_name: "data/HW_v7_l/params.yml"

random_split: True
split_tr_tst_val: [0.8, 0.1, 0.1]
split_ran_seed: 42
comp_val_loss: False

max_eval_ep_len: 120
num_eval_ep: 200
batch_size: 64

lr: 0.001
use_scheduler: True
wt_decay: 0.0001
warmup_steps: 1000
max_train_iters: 100
num_updates_per_iter: 500
add_target_loss: False
a_tl: 1000

target_conditioning: True 
context_len: 70
n_blocks: 1
embed_dim: 8
n_heads: 4
dropout_p: 0.1

device: 'cuda'