env_name: "gym_examples/contGrid-v5"
state_dim: 3
action_dim: 1
action_range: [0, 6.28318]
F: 1
vel_field: "/home/rohit/Documents/Research/Planning_with_transformers/Decision_transformer/my-dec-transformer/data/DG3/raw_data/nT_120"
del_t: 1.
vmax_by_F: 2.
space_scale: 100
target_radius: 2

rtg_target: 60
rtg_scale: 1
dataset_name: "DG3"
dataset_path: "data/DG3/traj_data_for_model_5_trad2.pkl"
log_dir: "log"
params2_name: "data/DG3/params.yml"

split_tr_tst_val: [0.8, 0.1, 0.1]
split_ran_seed: 42
comp_val_loss: False

max_eval_ep_len: 120
num_eval_ep: 100
batch_size: 64

lr: 0.0001
wt_decay: 0
warmup_steps: 10000
max_train_iters: 30
num_updates_per_iter: 50

context_len: 60
n_blocks: 1
embed_dim: 8
n_heads: 1
dropout_p: 0.1

device: 'cuda'


  
  
 
