env_name: "gym_examples/contGrid-v6_1"
state_dim: 5
action_dim: 1
action_range: [0, 6.28318]
F: 1
vel_field: "/home/rohit/Documents/Research/Planning_with_transformers/Decision_transformer/my-dec-transformer/data/HW_v2/raw_data/nT_120"
del_t: 1.
vmax_by_F: 1
space_scale: 1
target_radius: 2

rtg_target: 70
rtg_scale: 1
dataset_name: "HW_v2"
dataset_path: "data/HW_v2/traj_data_for_model_6_trad2.pkl"
log_dir: "log"
params2_name: "data/HW_v2/params.yml"

split_tr_tst_val: [0.8, 0.1, 0.1]
split_ran_seed: 42
comp_val_loss: False

max_eval_ep_len: 120
num_eval_ep: 40
batch_size: 64

lr: 0.0001
wt_decay: 0
warmup_steps: 10000
max_train_iters: 40
num_updates_per_iter: 400

context_len: 50
n_blocks: 2
embed_dim: 8
n_heads: 1
dropout_p: 0.1

device: 'cuda'


  
  
 
